modLoader = "lowcodefml"
loaderVersion = "[1,)" # NF uses lowcodefml version 1
license = "GPL-3.0"
issueTrackerURL = "https://github.com/prometheusreengineering/minecraft-essential/issues"

[[mods]]
modId = "prometheus_essential"
version = "0.0.0" # using anything other than strict SemVer will crash minecraft
displayName = "Prometheus"
description = "${project.description}"
logoFile = "assets/prometheus/icon.png"
features = { java_version = "[8,)" }
displayURL = "https://github.com/prometheusreengineering/minecraft-essential"
authors = ["dxxxxy", "Cootshk"]

[[mixins]]
config = "prometheus.essential.mixins.json"

[[dependencies.prometheus_essential]]
modId = "essential"
reason = "Prometheus cannot patch Essential without Essential" # essential seems to use the same mod id for stage0, 1, and 2
type = "optional"
ordering="AFTER"
versionRange = "[1.3.6.0,)"

[[dependencies.prometheus_essential]]
modId = "minecraft"
type = "required"
# versionRange = "[1.13,)"
side = "CLIENT"
